alias websearch='w3m duckduckgo.com'
alias lgo='ls -FhNgo --group-directories-first'
alias lgox='ls -FhNgox --group-directories-first'
alias lgoa='l -FhNAgoX --group-directories-first'
alias lw='ls -FNw 2 --group-directories-first'
alias lwa='ls -FNAw 2 --group-directories-first'
alias lmw='ls -mNw 2 --group-directories-first'
alias pkg='sudo apt-get'
alias mkdir='mkdir -pv'
alias clear='clear; lgox; echo ""'

# some more ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
